/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_test_JNAPGID */

#ifndef _Included_com_test_JNAPGID
#define _Included_com_test_JNAPGID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_test_JNAPGID
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_test_JNAPGID_sayHello
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_test_JNAPGID
 * Method:    setsid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_test_JNAPGID_setsid
  (JNIEnv *, jclass);

/*
 * Class:     com_test_JNAPGID
 * Method:    setpgid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_test_JNAPGID_setpgid
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
